services:
  - type: web
    name: reserveringsapp-opmeer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6

